import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { SidebarProvider } from "@/components/SidebarProvider";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "swiper/bundle";
import "swiper/css";
import "./globals.css";

export const metadata: Metadata = {
	title: "유니고",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={` antialiased relative`}>
				<SidebarProvider>
					<Navbar />
					{children}
					<Footer />
					<Toaster position="top-right" />
				</SidebarProvider>
			</body>
		</html>
	);
}
